app = "reviewintel-prod"
primary_region = "ord"

[build]
  builder = "heroku"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 3000
  processes = ["app"]

  [services.http_checks]
    enabled = true
    interval = 10000
    timeout = 5000
    grace_period = "5s"
    method = "GET"
    path = "/"

[[services.ports]]
  port = 80
  handlers = ["http"]

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]
